{% set name = "smallestai" %}
{% set version = "3.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smallestai-{{ version }}.tar.gz
  sha256: 2fc1446a82f19b266015d58c8683694414d832d7f7969d2ea4ecbe6ad8a9473a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - aiofiles
    - requests
    - pydub
    - urllib3 >=1.25.3,<3.0.0
    - python-dateutil >=2.8.2
    - pydantic >=2
    - typing_extensions >=4.7.1

test:
  imports:
    - smallestai
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/smallest-inc/smallest-python-sdk
  summary: Official Python client for the Smallest AI API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jgyasu
